### ISSUE TITLE
sg::detail::scope_guard<Callback>::~scope_guard<Callback>() noexcept

### ISSUE THREAD

**Issue by blackStar1314** [ricab/scope_guard#15]
Why  destructor with "<Callback>", instead of sg::detail::scope_guard<Callback>::~scope_guard() noexcept

**Comment by ricab** [comment]
Hi @blackStar1314, I am not sure what you mean, but if you're suggesting removing the template param entirely, it doesn't work.

**Comment by blackStar1314** [comment]
Hi, rica:
       I'am glad that you reply to me.
       The following pictures:
  ***@***.***D762D7.D9771630]

***@***.***D762D6.3DFB6D10]


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ricardo ***@***.***>
发送时间: 2021年6月16日 17:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ricab/scope_guard] sg::detail::scope_guard<Callback>::~scope_guard<Callback>() noexcept (#15)


Hi @blackStar1314<https://github.com/blackStar1314>, I am not sure what you mean, but if you're suggesting removing the template param entirely, it doesn't work.

―

**Comment by ricab** [comment]
@blackStar1314 no pictures are visible :confused:

**Comment by blackStar1314** [comment]
Hi,
       Sorry, I try again.😣 Pay attention to attachments.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ricardo ***@***.***>
发送时间: 2021年6月16日 22:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ricab/scope_guard] sg::detail::scope_guard<Callback>::~scope_guard<Callback>() noexcept (#15)


@blackStar1314<https://github.com/blackStar1314> no pictures are visible 😕
